apiVersion: v2
appVersion: 1.33.0-alpha.7d0c444ef8981a611e64cf0e179f3a7ffeb0db53
description: Helm chart for istio ztunnel components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-ztunnel
- istio
name: ztunnel
sources:
- https://github.com/istio/istio
version: 1.33.0-alpha.7d0c444ef8981a611e64cf0e179f3a7ffeb0db53
