apiVersion: v2
appVersion: 1.33.0-alpha.7d0c444ef8981a611e64cf0e179f3a7ffeb0db53
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

